# Generated by Django 5.1.3 on 2024-11-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0002_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
