# Generated by Django 5.1.3 on 2024-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_remove_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
