# Generated by Django 5.1.3 on 2024-11-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0004_member_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
