# Generated by Django 5.1.3 on 2024-11-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0005_member_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
