# Generated by Django 5.1.3 on 2024-11-24 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0006_member_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_duration',
            field=models.CharField(choices=[('1 měsíc', '1 měsíc'), ('3 měsíce', '3 měsíce'), ('6 měsíců', '6 měsíců'), ('1 rok', '1 rok')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('vstup', 'vstupová'), ('čas', 'časová'), ('vip', 'VIP')], max_length=50),
        ),
    ]
