# Generated by Django 5.1.3 on 2024-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0008_alter_member_membership_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('vstupová', 'entry_type'), ('časová', 'time_type')], max_length=50),
        ),
    ]
