# Generated by Django 5.1.3 on 2024-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0009_alter_member_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='join_date',
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
