# Generated by Django 5.1.3 on 2024-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0010_remove_member_join_date_member_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('vstupová', 'vstupová'), ('časová', 'časová')], max_length=50),
        ),
    ]
