# Generated by Django 5.1.3 on 2024-11-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0012_member_remaining_entries_member_total_entries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='remaining_entries',
        ),
        migrations.RemoveField(
            model_name='member',
            name='total_entries',
        ),
        migrations.AddField(
            model_name='member',
            name='entries_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='entries_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
