# Generated by Django 5.1.3 on 2024-11-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0013_remove_member_remaining_entries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='entries_allowed',
        ),
        migrations.RemoveField(
            model_name='member',
            name='entries_used',
        ),
    ]
