# Generated by Django 5.1.3 on 2024-11-26 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('am_checkins', models.IntegerField(default=0)),
                ('pm_checkins', models.IntegerField(default=0)),
            ],
        ),
    ]
