# Generated by Django 5.1.3 on 2024-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincount',
            name='total_checkins',
            field=models.IntegerField(default=0),
        ),
    ]
