# Generated by Django 5.1.3 on 2024-11-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_checkincount_total_checkins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkincount',
            name='total_checkins',
        ),
    ]
