# Generated by Django 5.1.3 on 2024-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_checkincount_total_checkins'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincount',
            name='total_checkins',
            field=models.IntegerField(default=0),
        ),
    ]
